name: Build App

on: 
  workflow_dispatch:
  pull_request:
  push:
    branches: 
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v4
          with:
            go-version: '1.20'
            check-latest: true
        - run: go build ./...
